package lt.vu.mybatis.dao;

import lt.vu.mybatis.model.AgentProperty;
import lt.vu.mybatis.model.Property;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

import javax.enterprise.context.ApplicationScoped;
import java.util.List;

@ApplicationScoped
@Mapper
public interface AgentPropertyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.AGENT_PROPERTY
     *
     * @mbg.generated Sun Apr 13 11:27:33 EEST 2025
     */
    int insert(AgentProperty row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.AGENT_PROPERTY
     *
     * @mbg.generated Sun Apr 13 11:27:33 EEST 2025
     */
    List<AgentProperty> selectAll();

    List<Property> selectPropertiesByAgentId(@Param("agentId") int agentId);

}