package lt.vu.mybatis.dao;

import lt.vu.mybatis.model.Agent;
import org.mybatis.cdi.Mapper;

import javax.enterprise.context.ApplicationScoped;
import java.util.List;

@ApplicationScoped
@Mapper
public interface AgentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.AGENT
     *
     * @mbg.generated Sun Apr 13 11:27:33 EEST 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.AGENT
     *
     * @mbg.generated Sun Apr 13 11:27:33 EEST 2025
     */
    int insert(Agent row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.AGENT
     *
     * @mbg.generated Sun Apr 13 11:27:33 EEST 2025
     */
    Agent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.AGENT
     *
     * @mbg.generated Sun Apr 13 11:27:33 EEST 2025
     */
    List<Agent> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.AGENT
     *
     * @mbg.generated Sun Apr 13 11:27:33 EEST 2025
     */
    int updateByPrimaryKey(Agent row);
}