package lt.vu.mybatis.dao;

import lt.vu.mybatis.model.Owner;
import org.apache.ibatis.annotations.*;
import org.mybatis.cdi.Mapper;

import javax.enterprise.context.ApplicationScoped;
import java.util.List;

@ApplicationScoped
@Mapper
public interface OwnerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.OWNER
     *
     * @mbg.generated Sun Apr 13 11:27:33 EEST 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.OWNER
     *
     * @mbg.generated Sun Apr 13 11:27:33 EEST 2025
     */
    int insert(Owner row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.OWNER
     *
     * @mbg.generated Sun Apr 13 11:27:33 EEST 2025
     */
    Owner selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.OWNER
     *
     * @mbg.generated Sun Apr 13 11:27:33 EEST 2025
     */
    List<Owner> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.OWNER
     *
     * @mbg.generated Sun Apr 13 11:27:33 EEST 2025
     */
    Owner selectOwnerWithProperties(int id);

    List<Owner> selectAllWithProperties();
}