package lt.vu.mybatis.dao;

import lt.vu.mybatis.model.Property;
import org.mybatis.cdi.Mapper;

import javax.enterprise.context.ApplicationScoped;
import java.util.List;

@ApplicationScoped
@Mapper
public interface PropertyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PROPERTY
     *
     * @mbg.generated Sun Apr 13 11:27:33 EEST 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PROPERTY
     *
     * @mbg.generated Sun Apr 13 11:27:33 EEST 2025
     */
    int insert(Property row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PROPERTY
     *
     * @mbg.generated Sun Apr 13 11:27:33 EEST 2025
     */
    Property selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PROPERTY
     *
     * @mbg.generated Sun Apr 13 11:27:33 EEST 2025
     */
    List<Property> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PROPERTY
     *
     * @mbg.generated Sun Apr 13 11:27:33 EEST 2025
     */
    int updateByPrimaryKey(Property row);
}