package lt.vu.mybatis.model;

public class Agent {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.AGENT.ID
     *
     * @mbg.generated Sun Apr 13 11:27:33 EEST 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.AGENT.NAME
     *
     * @mbg.generated Sun Apr 13 11:27:33 EEST 2025
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.AGENT.PHONE
     *
     * @mbg.generated Sun Apr 13 11:27:33 EEST 2025
     */
    private String phoneNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.AGENT.ID
     *
     * @return the value of PUBLIC.AGENT.ID
     *
     * @mbg.generated Sun Apr 13 11:27:33 EEST 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.AGENT.ID
     *
     * @param id the value for PUBLIC.AGENT.ID
     *
     * @mbg.generated Sun Apr 13 11:27:33 EEST 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.AGENT.NAME
     *
     * @return the value of PUBLIC.AGENT.NAME
     *
     * @mbg.generated Sun Apr 13 11:27:33 EEST 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.AGENT.NAME
     *
     * @param name the value for PUBLIC.AGENT.NAME
     *
     * @mbg.generated Sun Apr 13 11:27:33 EEST 2025
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.AGENT.PHONE
     *
     * @return the value of PUBLIC.AGENT.PHONE
     *
     * @mbg.generated Sun Apr 13 11:27:33 EEST 2025
     */
    public String getPhone() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.AGENT.PHONE
     *
     * @param phone the value for PUBLIC.AGENT.PHONE
     *
     * @mbg.generated Sun Apr 13 11:27:33 EEST 2025
     */
    public void setPhone(String phone) {
        this.phoneNumber = phone;
    }
}