package lt.vu.mybatis.model;

public class AgentProperty {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.AGENT_PROPERTY.PROPERTY_ID
     *
     * @mbg.generated Sun Apr 13 11:27:33 EEST 2025
     */
    private Integer propertyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.AGENT_PROPERTY.AGENT_ID
     *
     * @mbg.generated Sun Apr 13 11:27:33 EEST 2025
     */
    private Integer agentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.AGENT_PROPERTY.PROPERTY_ID
     *
     * @return the value of PUBLIC.AGENT_PROPERTY.PROPERTY_ID
     *
     * @mbg.generated Sun Apr 13 11:27:33 EEST 2025
     */
    public Integer getPropertyId() {
        return propertyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.AGENT_PROPERTY.PROPERTY_ID
     *
     * @param propertyId the value for PUBLIC.AGENT_PROPERTY.PROPERTY_ID
     *
     * @mbg.generated Sun Apr 13 11:27:33 EEST 2025
     */
    public void setPropertyId(Integer propertyId) {
        this.propertyId = propertyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.AGENT_PROPERTY.AGENT_ID
     *
     * @return the value of PUBLIC.AGENT_PROPERTY.AGENT_ID
     *
     * @mbg.generated Sun Apr 13 11:27:33 EEST 2025
     */
    public Integer getAgentId() {
        return agentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.AGENT_PROPERTY.AGENT_ID
     *
     * @param agentId the value for PUBLIC.AGENT_PROPERTY.AGENT_ID
     *
     * @mbg.generated Sun Apr 13 11:27:33 EEST 2025
     */
    public void setAgentId(Integer agentId) {
        this.agentId = agentId;
    }
}