package lt.vu.mybatis.model;

public class Property {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PROPERTY.ID
     *
     * @mbg.generated Sun Apr 13 11:27:33 EEST 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PROPERTY.ADDRESS
     *
     * @mbg.generated Sun Apr 13 11:27:33 EEST 2025
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PROPERTY.PRICE
     *
     * @mbg.generated Sun Apr 13 11:27:33 EEST 2025
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PROPERTY.OWNER_ID
     *
     * @mbg.generated Sun Apr 13 11:27:33 EEST 2025
     */
    private Integer ownerId;

    private Owner owner;

    public Owner getOwner() {
        return owner;
    }

    public void setOwner(Owner owner) {
        this.owner = owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PROPERTY.ID
     *
     * @return the value of PUBLIC.PROPERTY.ID
     *
     * @mbg.generated Sun Apr 13 11:27:33 EEST 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PROPERTY.ID
     *
     * @param id the value for PUBLIC.PROPERTY.ID
     *
     * @mbg.generated Sun Apr 13 11:27:33 EEST 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PROPERTY.ADDRESS
     *
     * @return the value of PUBLIC.PROPERTY.ADDRESS
     *
     * @mbg.generated Sun Apr 13 11:27:33 EEST 2025
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PROPERTY.ADDRESS
     *
     * @param address the value for PUBLIC.PROPERTY.ADDRESS
     *
     * @mbg.generated Sun Apr 13 11:27:33 EEST 2025
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PROPERTY.PRICE
     *
     * @return the value of PUBLIC.PROPERTY.PRICE
     *
     * @mbg.generated Sun Apr 13 11:27:33 EEST 2025
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PROPERTY.PRICE
     *
     * @param price the value for PUBLIC.PROPERTY.PRICE
     *
     * @mbg.generated Sun Apr 13 11:27:33 EEST 2025
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PROPERTY.OWNER_ID
     *
     * @return the value of PUBLIC.PROPERTY.OWNER_ID
     *
     * @mbg.generated Sun Apr 13 11:27:33 EEST 2025
     */
    public Integer getOwnerId() {
        return ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PROPERTY.OWNER_ID
     *
     * @param ownerId the value for PUBLIC.PROPERTY.OWNER_ID
     *
     * @mbg.generated Sun Apr 13 11:27:33 EEST 2025
     */
    public void setOwnerId(Integer ownerId) {
        this.ownerId = ownerId;
    }
}