package io.github.gitagliaudyte.estamate.mybatis.dao;

import io.github.gitagliaudyte.estamate.mybatis.model.Agent;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface AgentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.AGENT
     *
     * @mbg.generated Mon Apr 07 12:41:48 EEST 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.AGENT
     *
     * @mbg.generated Mon Apr 07 12:41:48 EEST 2025
     */
    int insert(Agent row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.AGENT
     *
     * @mbg.generated Mon Apr 07 12:41:48 EEST 2025
     */
    Agent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.AGENT
     *
     * @mbg.generated Mon Apr 07 12:41:48 EEST 2025
     */
    List<Agent> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.AGENT
     *
     * @mbg.generated Mon Apr 07 12:41:48 EEST 2025
     */
    int updateByPrimaryKey(Agent row);
}