package io.github.gitagliaudyte.estamate.mybatis.dao;

import io.github.gitagliaudyte.estamate.mybatis.model.Owner;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface OwnerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.OWNER
     *
     * @mbg.generated Mon Apr 07 12:41:48 EEST 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.OWNER
     *
     * @mbg.generated Mon Apr 07 12:41:48 EEST 2025
     */
    int insert(Owner row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.OWNER
     *
     * @mbg.generated Mon Apr 07 12:41:48 EEST 2025
     */
    Owner selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.OWNER
     *
     * @mbg.generated Mon Apr 07 12:41:48 EEST 2025
     */
    List<Owner> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.OWNER
     *
     * @mbg.generated Mon Apr 07 12:41:48 EEST 2025
     */
    int updateByPrimaryKey(Owner row);
}